[package]
name = "wgpu_terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.14.3", features = ["derive" ] }
cgmath = { workspace = true, features = ["bytemuck"] }
# terminal
vt100 = { version = "0.0.1", path = "../../src/vt100" }
terminal = { version = "0.0.1", path = "../../src/terminal" }
terminal_process = { version = "0.0.1", path = "../../src/terminal_process" }
crossbeam-channel = { version = "0.5" }
# graphics
fontdue = { workspace = true }
tile_renderer = { version = "0.0.1", path = "../tile_renderer" }
wgpu = { workspace = true }
winit = { version = "0.29.0" }
# logging
log = { version = "0.4.20" }
simple_logger = { version = "4.3.3", features = ["colors", "threads", "stderr"] }
# executable
clap = { version = "4.5.1", features = ["derive"] }
pollster = { version = "0.3.0" }
anyhow = { version = "1.0.80" }

[target.'cfg(windows)'.dependencies]
conpty = { version = "0.0.1", path = "../../src/conpty" }
windows = { version = "0.53.0", features = ["Win32_System_Console", "Win32_UI_WindowsAndMessaging"] }

[target.'cfg(unix)'.dependencies]
unix_pty = { version = "0.0.1", path = "../../src/unix_pty" }
