[package]
name = "tile_renderer"
version = "0.0.1"
edition = "2021"

[dependencies]
bytemuck = { version = "1.14.3", features = ["derive" ] }
cgmath = { workspace = true, features = ["bytemuck"] }
fontdue = { workspace = true }
wgpu = { workspace = true }
log = { version = "0.4.20" }
