#[derive(Clone,Copy,Default,Debug,PartialEq,Eq)]
pub struct Rgb8 {
    pub r: u8,
    pub g: u8,
    pub b: u8,
}

#[derive(Clone,Copy,Debug,PartialEq,Eq)]
pub enum GraphicStyle {
    ResetAll,
    EnableBold,
    EnableDim,
    EnableItalic,
    EnableUnderline,
    EnableBlinking,
    EnableInverse,
    EnableHidden,
    EnableStrikethrough,
    DisableWeight,
    DisableItalic,
    DisableUnderline,
    DisableBlinking,
    DisableInverse,
    DisableHidden,
    DisableStrikethrough,
    ForegroundBlack,
    ForegroundRed,
    ForegroundGreen,
    ForegroundYellow,
    ForegroundBlue,
    ForegroundMagenta,
    ForegroundCyan,
    ForegroundWhite,
    ForegroundExtended,
    ForegroundDefault,
    BackgroundBlack,
    BackgroundRed,
    BackgroundGreen,
    BackgroundYellow,
    BackgroundBlue,
    BackgroundMagenta,
    BackgroundCyan,
    BackgroundWhite,
    BackgroundExtended,
    BackgroundDefault,
    BrightForegroundBlack,
    BrightForegroundRed,
    BrightForegroundGreen,
    BrightForegroundYellow,
    BrightForegroundBlue,
    BrightForegroundMagenta,
    BrightForegroundCyan,
    BrightForegroundWhite,
    BrightBackgroundBlack,
    BrightBackgroundRed,
    BrightBackgroundGreen,
    BrightBackgroundYellow,
    BrightBackgroundBlue,
    BrightBackgroundMagenta,
    BrightBackgroundCyan,
    BrightBackgroundWhite,
}

impl GraphicStyle {
    pub(crate) fn try_from_u16(v: u16) -> Option<Self> {
        match v {
              0 => Some(Self::ResetAll),
              1 => Some(Self::EnableBold),
              2 => Some(Self::EnableDim),
              3 => Some(Self::EnableItalic),
              4 => Some(Self::EnableUnderline),
              5 => Some(Self::EnableBlinking),
              7 => Some(Self::EnableInverse),
              8 => Some(Self::EnableHidden),
              9 => Some(Self::EnableStrikethrough),
             22 => Some(Self::DisableWeight),
             23 => Some(Self::DisableItalic),
             24 => Some(Self::DisableUnderline),
             25 => Some(Self::DisableBlinking),
             27 => Some(Self::DisableInverse),
             28 => Some(Self::DisableHidden),
             29 => Some(Self::DisableStrikethrough),
             30 => Some(Self::ForegroundBlack),
             31 => Some(Self::ForegroundRed),
             32 => Some(Self::ForegroundGreen),
             33 => Some(Self::ForegroundYellow),
             34 => Some(Self::ForegroundBlue),
             35 => Some(Self::ForegroundMagenta),
             36 => Some(Self::ForegroundCyan),
             37 => Some(Self::ForegroundWhite),
             38 => Some(Self::ForegroundExtended),
             39 => Some(Self::ForegroundDefault),
             40 => Some(Self::BackgroundBlack),
             41 => Some(Self::BackgroundRed),
             42 => Some(Self::BackgroundGreen),
             43 => Some(Self::BackgroundYellow),
             44 => Some(Self::BackgroundBlue),
             45 => Some(Self::BackgroundMagenta),
             46 => Some(Self::BackgroundCyan),
             47 => Some(Self::BackgroundWhite),
             48 => Some(Self::BackgroundExtended),
             49 => Some(Self::BackgroundDefault),
             90 => Some(Self::BrightForegroundBlack),
             91 => Some(Self::BrightForegroundRed),
             92 => Some(Self::BrightForegroundGreen),
             93 => Some(Self::BrightForegroundYellow),
             94 => Some(Self::BrightForegroundBlue),
             95 => Some(Self::BrightForegroundMagenta),
             96 => Some(Self::BrightForegroundCyan),
             97 => Some(Self::BrightForegroundWhite),
            100 => Some(Self::BrightBackgroundBlack),
            101 => Some(Self::BrightBackgroundRed),
            102 => Some(Self::BrightBackgroundGreen),
            103 => Some(Self::BrightBackgroundYellow),
            104 => Some(Self::BrightBackgroundBlue),
            105 => Some(Self::BrightBackgroundMagenta),
            106 => Some(Self::BrightBackgroundCyan),
            107 => Some(Self::BrightBackgroundWhite),
            _ => None,
        }
    }
}

