[package]
name = "circular_buffer_channel"
version = "0.0.1"
edition = "2021"

[dependencies]
log = { version = "0.4.20" }
circular_buffer = { version = "0.0.1", path = "../circular_buffer" }

[dev-dependencies]
test-log = "0.2.15"
