name: x86-ubuntu

on:
  workflow_dispatch:
  push:
    branches: [ "master", "main", "dev" ]

env:
  BUILD_TYPE: release
  PACKAGE_DIR: wgpu_terminal_ubuntu_x64

jobs:
  skip_check:
    continue-on-error: false
    runs-on: ubuntu-22.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: 'same_content'
        cancel_others: 'true'
        skip_after_successful_duplicate: 'true'
        paths_ignore: '["**/README.md", "**/docs/**", "**/LICENSE.txt"]'
        do_not_skip: '["workflow_dispatch", "schedule"]'

  build:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive 

    - name: Test
      shell: bash
      run: cargo test --profile ${{env.BUILD_TYPE}}

    - name: Build
      shell: bash
      run: cargo build --profile ${{env.BUILD_TYPE}}

    - name: Copy files
      shell: bash
      run: |
        mkdir -p ${{env.PACKAGE_DIR}}
        cp -rf res/ ${{env.PACKAGE_DIR}}/
        cp ./target/${{env.BUILD_TYPE}}/wgpu_terminal ${{env.PACKAGE_DIR}}/
        cp ./README.md ${{env.PACKAGE_DIR}}/

    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.PACKAGE_DIR}}
        path: ${{github.workspace}}/${{env.PACKAGE_DIR}}
